import Head from "next/head";



// Bootstrap
import 'bootstrap/dist/css/bootstrap.min.css';



// Font Link Css
import '../styles/landing-pages-css/landing-common-css/landing-font.css';

// Landing Page Css

import '../styles/landing-pages-css/landing-common-css/landing-common.css';

import '../styles/landing-pages-css/landing-1.css';

import '../styles/landing-pages-css/landing-2.css';

import '../styles/landing-pages-css/landing-3.css';

import '../styles/landing-pages-css/landing-4.css';

import '../styles/landing-pages-css/landing-5.css';

import '../styles/landing-pages-css/landing-6.css';

import '../styles/landing-pages-css/landing-7.css';

import '../styles/landing-pages-css/landing-8.css';

import '../styles/landing-pages-css/landing-9.css';

import '../styles/landing-pages-css/landing-10.css';

import '../styles/landing-pages-css/landing-12.css';

import '../styles/landing-pages-css/landing-11.css';

import '../styles/landing-pages-css/landing-13.css';

import '../styles/landing-pages-css/landing-14.css';

import '../styles/landing-pages-css/landing-15.css';

import '../styles/landing-pages-css/landing-16.css';

import '../styles/landing-pages-css/landing-17.css';

import '../styles/landing-pages-css/landing-18.css';

import '../styles/landing-pages-css/landing-19.css';

import '../styles/landing-pages-css/landing-20.css';

import '../styles/landing-pages-css/landing-21.css';

import '../styles/landing-pages-css/landing-22.css';

import '../styles/landing-pages-css/landing-23.css';

import '../styles/landing-pages-css/landing-24.css';

import '../styles/landing-pages-css/landing-25.css';

import '../styles/landing-pages-css/landing-26.css';

import '../styles/landing-pages-css/landing-27.css';

import '../styles/landing-pages-css/landing-28.css';

import '../styles/landing-pages-css/landing-29.css';




// Multipage Css

import '../styles/multipage/multipage-1.css'
import '../styles/multipage/multipage-common.css'











function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Funnel Liner Preview</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="images/favicon.png" />
      </Head>

        <Component {...pageProps} />
        
    </>
  );
}

export default MyApp;